language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.4"
  - "node"
sudo: false
install: (cd nodejs && npm install)
script:
  - (cd nodejs && npm test)
notifications:
  email:
    on_success: change
    on_failure: change
